services:
  keybr:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - keybr_data:/etc/keybr/state/keybr
      - ./.env:/etc/keybr/env
#    ports:
#      - 30044:3000
    restart: unless-stopped
volumes:
  keybr_data:
  
